# fly.toml app configuration file generated for purple-surf-7233 on 2023-06-20T23:29:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "purple-surf-7233"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
